version: 2.1

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

  # A parameter per package
  api:
    type: boolean
    default: false
  nxsonardemo:
    type: boolean
    default: false
  data:
    type: boolean
    default: false
  ui:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

  build:
    parameters:
      package_path:
        type: string
      package_name:
        type: string

    executor: node
    working_directory: ~/project/<< parameters.package_path >>/<< parameters.package_name >>

    steps:
      - checkout:
          path: ~/project
      # This step is added only to show that we are in the package directory
      - run:
          name: Content
          command: |
            cat README.md
            echo "<< parameters.package_path >>/<< parameters.package_name >> built." > build.txt
      - run:
          name: Build
          command: echo "Build << parameters.package_path >>/<< parameters.package_name >> ..."
      - persist_to_workspace:
          root: ~/project
          paths:
            - << parameters.package_path >>/<< parameters.package_name >>

  deploy:
    parameters:
      package_path:
        type: string
      package_name:
        type: string

    executor: node
    working_directory: ~/project/<< parameters.package_path >>/<< parameters.package_name >>

    steps:
      - attach_workspace:
          at: ~/project
      # This step is added to show that files are available from the build job.
      - run:
          name: Content to deploy
          command: ls && cat build.txt
      - deploy:
          name: Deploy
          command: echo "Deploying << parameters.package_path >>/<< parameters.package_name >> ..."

workflows:
  version: 2

  # The main workflow responsible for triggering all other workflows
  # in which changes are detected.
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

  # Workflows defined for each package.

  api:
    when: << pipeline.parameters.api >>
    jobs:
      - build:
          name: api-build
          package_path: apps
          package_name: api
      - deploy:
          name: api-deploy
          package_path: apps
          package_name: api
          requires:
            - api-build

  nxsonardemo:
    when: << pipeline.parameters.nxsonardemo >>
    jobs:
      - build:
          name: nxsonardemo-build
          package_path: apps
          package_name: nxsonardemo
      - deploy:
          name: nxsonardemo-deploy
          package_path: apps
          package_name: nxsonardemo
          requires:
            - nxsonardemo-build

  data:
    when: << pipeline.parameters.data >>
    jobs:
      - build:
          name: data-build
          package_path: libs
          package_name: data
      - deploy:
          name: data-deploy
          package_path: libs
          package_name: data
          requires:
            - data-build

  ui:
    when: << pipeline.parameters.ui >>
    jobs:
      - build:
          name: ui-build
          package_path: libs
          package_name: ui
      - deploy:
          name: ui-deploy
          package_path: libs
          package_name: ui
          requires:
            - ui-build
